ALTER TABLE `properties_decorations`
    ADD COLUMN IF NOT EXISTS `item` VARCHAR(100) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS `item_metadata` LONGTEXT DEFAULT NULL;

ALTER TABLE `properties_apartment_decorations`
    ADD COLUMN IF NOT EXISTS `item` VARCHAR(100) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS `item_metadata` LONGTEXT DEFAULT NULL;
